apiVersion: v1
kind: Pod
metadata:
  name: $kernel_username-$kernel_id
  namespace: $namespace
  labels:
    kernel_id: $kernel_id
    app: enterprise-gateway
spec:
  restartPolicy: Never
  containers:
  - env:
    - name: EG_RESPONSE_ADDRESS
      value: $response_address
    - name: KERNEL_CONNECTION_FILENAME
      value: $connection_filename
    - name: KERNEL_LANGUAGE
      value: $language
    - name: NO_SPARK_CONTEXT
      value: $no_spark_context
    image: $docker_image
    name: $kernel_username-$kernel_id
    command: ["/usr/local/share/jupyter/kernels/bootstrap-kernel.sh"]