apiVersion: v1
kind: Service
metadata:
  labels:
    kernel_id: $kernel_id
    app: enterprise-gateway
  name: eg-$kernel_id
  namespace: $namespace
spec:
  ports:
  - name: comm-port
    port: $comm_port
    targetPort: $comm_port
  - name: stdin-port
    port: $stdin_port
    targetPort: $stdin_port
  - name: control-port
    port: $control_port
    targetPort: $control_port
  - name: hb-port
    port: $hb_port
    targetPort: $hb_port
  - name: shell-port
    port: $shell_port
    targetPort: $shell_port
  - name: iopub-port
    port: $iopub_port
    targetPort: $iopub_port
  selector:
    kernel_id: $kernel_id
  sessionAffinity: ClientIP
  type: ClusterIP
