# This file defines the Kubernetes objects necessary for Enterprise Gateway to run witihin Kubernetes.
#
# Kernelspecs can be exposed via a PersistentVolume (and corresponding PersistentVolumeClaim).  Below
# is an example of such a PV relative to NFS.  It requires that all nodes within the Kubernetes cluster
# are mounting the NFS directory from the specified server.  To enable this functionality, uncomment the
# corresponding stanzas for PersistentVolume, PersistentVolumeClaim, and the volumeMounts and volumes
# stanzas in the Enterprise-Gateway deployment.  In addition, the volumeMounts and volumes stanzas
# in any kernel-pod.yaml files (e.g., python_kubernetes) should also be uncommented.
#
#kind: PersistentVolume
#apiVersion: v1
#metadata:
#  name: kernelspecs-pv
#  labels:
#    app: enterprise-gateway
#spec:
#  capacity:
#    storage: 10Mi
#  accessModes:
#    - ReadOnlyMany
#  nfs:
#    server: <IPv4>
#    path: /usr/local/share/jupyter/kernels
#---
#kind: PersistentVolumeClaim
#apiVersion: v1
#metadata:
#  name: kernelspecs-pvc
#  labels:
#    app: enterprise-gateway
#spec:
#  accessModes:
#    - ReadOnlyMany
#  resources:
#    requests:
#      storage: 10Mi
#  selector:
#    matchLabels:
#      app: enterprise-gateway
#---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: enterprise-gateway
  name: enterprise-gateway
spec:
  ports:
  - name: http
    port: 8888
    targetPort: 8888
  selector:
    gateway-selector: enterprise-gateway
  sessionAffinity: ClientIP
  type: NodePort
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: enterprise-gateway
  labels:
    gateway-selector: enterprise-gateway
    app: enterprise-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      gateway-selector: enterprise-gateway
  template:
    metadata:
      labels:
        gateway-selector: enterprise-gateway
        app: enterprise-gateway
    spec:
      containers:
      - env:
        - name: EG_KUBERNETES_NAMESPACE
          value: "default"
        - name: EG_TUNNELING_ENABLED
          value: "False"
        - name: EG_CULL_IDLE_TIMEOUT
          value: "600"
        - name: EG_LOG_LEVEL
          value: "DEBUG"
        image: elyra/kubernetes-enterprise-gateway:dev
        name: enterprise-gateway
        args: ["--elyra"]
        ports:
        - containerPort: 8888
# Uncomment to enable PV for kernelspecs
#        volumeMounts:
#        - mountPath: /usr/local/share/jupyter/kernels
#          name: kernelspecs
#      volumes:
#      - name: kernelspecs
#        persistentVolumeClaim:
#          claimName: kernelspecs-pvc