name: kernel_gateway_docs
dependencies:
- sphinx>=1.3
- sphinx_rtd_theme
- jinja2
- tornado
- nbformat
- jupyter_client
- notebook
- kernel_gateway
- ipykernel
- pip:
    - sphinxcontrib_spelling
    - pyenchant